const INTEGRATIONS = [
  {
    key: "facebook",
    slug: "facebook-lead",
    name: "Facebook Lead",
    description: "Capture Facebook Lead Ads into the CRM automatically.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "website_lead",
    slug: "website-lead",
    name: "Website Lead",
    description: "Push website enquiry forms straight into the lead pipeline.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "indiamart",
    slug: "indiamart",
    name: "IndiaMart",
    description: "Receive buyer enquiries from IndiaMart.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "99acres",
    slug: "99acres",
    name: "99acres",
    description: "Sync 99acres property enquiries.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "google_ads",
    slug: "google-ads",
    name: "Google Ads",
    description: "Ingest leads generated by Google Ads campaigns.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "housing",
    slug: "housing",
    name: "Housing.com",
    description: "Sync property enquiries from Housing.com.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "just_dial",
    slug: "just-dial",
    name: "Just Dial",
    description: "Bring Just Dial enquiries into the CRM automatically.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "magicbricks",
    slug: "magicbricks",
    name: "MagicBricks",
    description: "Capture MagicBricks property leads.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "software_suggest",
    slug: "software-suggest",
    name: "Software Suggest",
    description: "Sync enquiry submissions from Software Suggest.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "tradeindia",
    slug: "tradeindia",
    name: "TradeIndia",
    description: "Receive TradeIndia business enquiries in real time.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "wordpress",
    slug: "wordpress-website",
    name: "WordPress",
    description: "Connect WordPress forms and landing pages to the CRM.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "google_form",
    slug: "google-form",
    name: "Google Form",
    description: "Route Google Form submissions into the CRM.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "systeme_io",
    slug: "systeme-io",
    name: "Systeme.io",
    description: "Capture funnel and form submissions from Systeme.io.",
    requiredFields: ["name", "phone"],
  },
  {
    key: "referral",
    slug: "referral",
    name: "Referral",
    description: "Track referral leads from offline or partner channels.",
    requiredFields: ["name", "phone"],
  },
];

function getIntegrationByKey(value) {
  return INTEGRATIONS.find((integration) => integration.key === value) || null;
}

function getIntegrationBySlug(value) {
  return INTEGRATIONS.find((integration) => integration.slug === value) || null;
}

function getIntegrationByKeyOrSlug(value) {
  return getIntegrationByKey(value) || getIntegrationBySlug(value);
}

module.exports = {
  INTEGRATIONS,
  getIntegrationByKey,
  getIntegrationBySlug,
  getIntegrationByKeyOrSlug,
};
