const COMMON_FIELDS = [
  "name",
  "phone",
  "email",
  "company_name",
  "message",
  "assigned_to",
  "follow_up_date",
];

function createIntegration(config) {
  return {
    badge: null,
    supportedFields: COMMON_FIELDS,
    samplePayload: {
      name: "Aman Sharma",
      phone: "+91 98765 43210",
      email: "aman@example.com",
      company_name: "Fitness Prospect",
      message: "Interested in a demo and pricing details.",
      assigned_to: "clerk_user_id_or_internal_user_id",
    },
    ...config,
    href: `/integrations/${config.slug}`,
  };
}

export const INTEGRATIONS = [
  createIntegration({
    key: "facebook",
    slug: "facebook-lead",
    title: "Facebook Lead",
    icon: "fab fa-facebook",
    desc: "Pull Facebook Lead Ads directly into your CRM in real time.",
    color: "#eff6ff",
    accent: "#1877F2",
    badge: "Most Popular",
    setupSteps: [
      "Open Facebook Lead Ads or your automation tool for the page or campaign.",
      "Configure a webhook or automation action that posts each lead to your FitnessVitness CRM webhook URL.",
      "Send the shared integration secret in the `x-integration-secret` header or as a bearer token.",
      "Map the lead name and mobile number at minimum, then pass email, company, and notes when available.",
    ],
    crmOutcome: [
      "Each lead lands in the CRM with source `facebook`.",
      "The lead is assigned to the mapped user or falls back to your default CRM owner.",
      "Raw webhook payloads are logged for troubleshooting.",
    ],
  }),
  createIntegration({
    key: "website_lead",
    slug: "website-lead",
    title: "Website Lead",
    icon: "fas fa-globe",
    desc: "Embed a lead form on your website and sync enquiries automatically.",
    color: "#f0fdf4",
    accent: "#15803d",
    setupSteps: [
      "Point your website form action or JavaScript submit handler to the CRM webhook URL.",
      "Send JSON with at least `name` and `phone`; include message, email, and company details whenever possible.",
      "Protect the endpoint with the shared integration secret so only your website can submit leads.",
      "Use `assigned_to` if you want specific forms or landing pages to route to a particular sales owner.",
    ],
    crmOutcome: [
      "Website enquiries appear as normal CRM leads instead of staying in email inboxes.",
      "Marketing landing pages and the sales team stay on the same pipeline.",
      "You can later segment by the `website_lead` source in reports and dashboards.",
    ],
  }),
  createIntegration({
    key: "indiamart",
    slug: "indiamart",
    title: "IndiaMart",
    icon: "fas fa-store",
    desc: "Automatically import buyer enquiries from your IndiaMart listing.",
    color: "#fff7e6",
    accent: "#E87722",
    badge: "Popular",
    setupSteps: [
      "Use IndiaMart lead forwarding, a webhook bridge, or an automation platform that receives IndiaMart enquiries.",
      "Forward the payload to the CRM webhook URL for the `indiamart` source.",
      "Map buyer name and mobile number first, then include email, company, and requirement text.",
      "Test with one real enquiry before enabling the automation for the whole account.",
    ],
    crmOutcome: [
      "Buyer enquiries are stored with source `indiamart` for easy filtering.",
      "The sales team can track follow-ups, notes, reminders, and conversions from one place.",
      "Webhook payloads are logged so failed mappings are easier to debug.",
    ],
  }),
  createIntegration({
    key: "99acres",
    slug: "99acres",
    title: "99acres",
    icon: "fas fa-building",
    desc: "Sync property leads from 99acres straight into your pipeline.",
    color: "#fdf4ff",
    accent: "#7e22ce",
    setupSteps: [
      "Use 99acres lead forwarding or your middleware automation to call the CRM webhook.",
      "Send contact name and phone at minimum; add property details in `message` or `notes`.",
      "Use `assigned_to` to route specific properties or projects to dedicated agents.",
      "Validate one test enquiry so the team sees the lead appear with the correct owner.",
    ],
    samplePayload: {
      name: "Rahul Verma",
      phone: "+91 90000 12345",
      email: "rahul@example.com",
      company_name: "Home Buyer",
      message: "Interested in 2 BHK near Ahmedabad. Budget 65L.",
      assigned_to: "clerk_user_id_or_internal_user_id",
    },
    crmOutcome: [
      "Property enquiries enter the lead pipeline with source `99acres`.",
      "Sales owners can manage site visits, meetings, notes, and follow-ups from the CRM.",
      "Future reporting can separate 99acres performance from Housing or MagicBricks.",
    ],
  }),
  createIntegration({
    key: "google_ads",
    slug: "google-ads",
    title: "Google Ads",
    icon: "fab fa-google",
    desc: "Capture Google Ads leads without any manual copy-pasting.",
    color: "#fff1f2",
    accent: "#ea4335",
    setupSteps: [
      "Use Google Ads lead form extensions with a webhook-compatible middleware or automation.",
      "Forward each submission to the CRM webhook URL for `google_ads`.",
      "Include campaign context in `message`, `campaign`, or `campaign_name` so the CRM keeps the source detail.",
      "Review the CRM lead after a test submit before turning the automation on for all campaigns.",
    ],
    crmOutcome: [
      "Ad responses arrive in the CRM immediately with source `google_ads`.",
      "Campaign context can be stored inside notes for later analysis.",
      "No one has to manually export CSV leads from the ads dashboard.",
    ],
  }),
  createIntegration({
    key: "housing",
    slug: "housing",
    title: "Housing.com",
    icon: "fas fa-home",
    desc: "Import property enquiries from Housing.com automatically.",
    color: "#eff6ff",
    accent: "#1d4ed8",
    setupSteps: [
      "Use Housing.com lead forwarding or an external automation connector.",
      "Post incoming enquiries to the CRM webhook with the integration secret.",
      "Pass property and project context in `message`, `project`, or `property_name`.",
      "Test the route with one enquiry and confirm assignment in the CRM before going live.",
    ],
    crmOutcome: [
      "Housing leads are tagged with source `housing` in the CRM.",
      "Your team can work property portals from one follow-up workflow.",
      "The stored webhook logs help trace missing fields quickly.",
    ],
  }),
  createIntegration({
    key: "just_dial",
    slug: "just-dial",
    title: "Just Dial",
    icon: "fas fa-phone-volume",
    desc: "Connect Just Dial to get every enquiry routed into your CRM.",
    color: "#fff7e6",
    accent: "#b45309",
    setupSteps: [
      "Receive Just Dial enquiries via email parser, middleware, or direct lead connector.",
      "Convert the payload to JSON and push it to the CRM webhook URL.",
      "Keep phone and lead name mandatory; add requirement text inside `message`.",
      "Assign a specific owner when needed using `assigned_to`.",
    ],
    crmOutcome: [
      "Just Dial responses become searchable CRM leads instead of being buried in email.",
      "Lead ownership and reminders stay inside the same system.",
      "The source key `just_dial` remains available for future dashboards and reports.",
    ],
  }),
  createIntegration({
    key: "magicbricks",
    slug: "magicbricks",
    title: "MagicBricks",
    icon: "fas fa-city",
    desc: "Automatically sync leads from your MagicBricks property listings.",
    color: "#f0fdf4",
    accent: "#065f46",
    setupSteps: [
      "Use MagicBricks lead export, forwarding, or a middleware connector to call the CRM webhook.",
      "Include listing or project information in `message` so the CRM record has property context.",
      "Make sure the webhook sends the shared secret for authorization.",
      "Run a test enquiry and verify the lead owner and source in the CRM.",
    ],
    crmOutcome: [
      "MagicBricks leads enter your pipeline with source `magicbricks`.",
      "Agents can track notes, meetings, reminders, and stage changes in one workflow.",
      "Troubleshooting is easier because the raw webhook payload is retained.",
    ],
  }),
  createIntegration({
    key: "software_suggest",
    slug: "software-suggest",
    title: "Software Suggest",
    icon: "fas fa-laptop-code",
    desc: "Receive Software Suggest enquiries directly in your lead pipeline.",
    color: "#fdf4ff",
    accent: "#6b21a8",
    setupSteps: [
      "Connect Software Suggest lead forwarding through an automation layer or custom webhook script.",
      "Post enquiry data into the CRM webhook URL for `software_suggest`.",
      "Send product interest or software category details in `message`.",
      "Use a test enquiry first so the lead shape is validated in the CRM.",
    ],
    crmOutcome: [
      "Software marketplace enquiries stop living outside the main CRM pipeline.",
      "Source tracking remains intact for reporting and team review.",
      "Lead payloads are preserved in integration logs for debugging.",
    ],
  }),
  createIntegration({
    key: "tradeindia",
    slug: "tradeindia",
    title: "TradeIndia",
    icon: "fas fa-industry",
    desc: "Import B2B leads from TradeIndia with zero manual effort.",
    color: "#fff7e6",
    accent: "#c2410c",
    setupSteps: [
      "Receive TradeIndia buyer enquiries through direct forwarding or an automation tool.",
      "Forward each enquiry to the CRM webhook URL with the integration secret.",
      "Capture buyer requirement text in `message` and company name in `company_name`.",
      "After testing, point all new enquiries to the CRM endpoint.",
    ],
    crmOutcome: [
      "TradeIndia responses arrive with source `tradeindia`.",
      "The sales team can assign tasks and reminders immediately after ingestion.",
      "A single CRM pipeline now covers B2B and portal leads together.",
    ],
  }),
  createIntegration({
    key: "wordpress",
    slug: "wordpress-website",
    title: "WordPress",
    icon: "fab fa-wordpress",
    desc: "Connect any WordPress contact or enquiry form to your CRM.",
    color: "#eff6ff",
    accent: "#21759b",
    setupSteps: [
      "Use your form plugin webhook action or a small custom POST request from WordPress.",
      "Send submissions to the CRM webhook URL for the `wordpress` source.",
      "Map `name` and `phone` first, then pass email, company, and message fields.",
      "Store the shared secret in WordPress config so only trusted submissions reach the CRM.",
    ],
    crmOutcome: [
      "Website and landing-page forms go directly into your sales workflow.",
      "Lead owners can be assigned per form, campaign, or page when needed.",
      "The CRM keeps a clear distinction between WordPress and other lead sources.",
    ],
  }),
  createIntegration({
    key: "google_form",
    slug: "google-form",
    title: "Google Form",
    icon: "fab fa-google",
    desc: "Route Google Form submissions straight into your lead pipeline.",
    color: "#fff1f2",
    accent: "#0f9d58",
    setupSteps: [
      "Use Apps Script, Make, Zapier, or another bridge to send Google Form responses to the webhook URL.",
      "Map form answers to the CRM JSON structure with at least `name` and `phone`.",
      "Use `message` for free-text responses or qualification notes.",
      "Test once from the live form before using it in production campaigns.",
    ],
    crmOutcome: [
      "Google Form responses become CRM leads without spreadsheets.",
      "Sales and marketing teams work from one source of truth.",
      "The source `google_form` stays available for later reporting.",
    ],
  }),
  createIntegration({
    key: "systeme_io",
    slug: "systeme-io",
    title: "Systeme.io",
    icon: "fas fa-bolt",
    desc: "Sync leads and funnel submissions from Systeme.io automatically.",
    color: "#f0fdf4",
    accent: "#1e40af",
    setupSteps: [
      "Create a funnel automation or webhook action inside Systeme.io.",
      "Send each funnel submission to the CRM webhook URL for `systeme_io`.",
      "Use `message`, `campaign`, or `tag` to preserve funnel context for the sales team.",
      "Confirm with one test signup before enabling the automation for all traffic.",
    ],
    crmOutcome: [
      "Funnel leads appear in the CRM immediately after submission.",
      "Your team can act on course, offer, or campaign intent without switching tools.",
      "Systeme.io performance can later be reported separately from other channels.",
    ],
  }),
];

export function getIntegrationBySlug(slug) {
  return INTEGRATIONS.find((integration) => integration.slug === slug) || null;
}
